# Generated by Django 3.2.18 on 2023-03-19 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20230319_1216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productno',
            new_name='Product',
        ),
    ]
